### ISSUE TITLE
Alternative source for data

### ISSUE THREAD

**Issue by jaimergp** [knudmoeller/berlin_corona_cases#1]
Seems like https://www.berlin.de/corona/lagebericht/desktop/corona.html has a faster update rate!

The divs are correctly id'ed, so it should be easy to parse too:

![image](https://user-images.githubusercontent.com/2559438/94041835-0f978c80-fdcb-11ea-9c25-d4b5e098a895.png)

**Comment by knudmoeller** [comment]
Thanks! Yeah, I noticed, the dashboard you have linked to has actually replaced the daily press releases. In fact, I have stopped using the Python/Scrapy-parser (since there is nothing to parse anymore) and written a new parser for the dashboard. I you look at the JSON-files in `data/target`, you'll notice that the `source`-attribute now points to the dashboard. E.g.:

https://github.com/knudmoeller/berlin_corona_cases/blob/7b54e045fb6b8dc379cd2fca6da3355ad517558b/data/target/berlin_corona_traffic_light.latest.json#L2

I'm using a completely new parser for this based on Ruby/nokogiri (no particular reason, it was just easiest for me to do it that way). I just haven't pushed the code for that yet, because I didn't get around to documenting the changes in the readme.

I might just drop the code in its current state to a different branch, if you want to have a look at it!

**Comment by knudmoeller** [comment]
And here it is!

https://github.com/knudmoeller/berlin_corona_cases/tree/feature/scrape_dashboard

Sorry for the slightly messed up commit history...

The parser itself is here: https://github.com/knudmoeller/berlin_corona_cases/blob/feature/scrape_dashboard/bin/scrape_dashboard.rb

**Comment by jaimergp** [comment]
Oh, I see! I hadn't realized `source` was already pointing to the new URL.  Then, no issue! 👍 

I did realize that the data updates are pushed manually, tho. Have you considered automating it with GitHub Actions or similar? I could help there if you were interested!

**Comment by knudmoeller** [comment]
Github actions sound cool! I had a look at them for automating something like sending a tweet every time I push updates, but I decided against using them (too complicated for what I want to do). Also, I guess that's not what you mean. Could you explain what you have in mind?

**Comment by jaimergp** [comment]
It would run as a cron job to check if new numbers are available, then it would render the new JSON and then commit the changes.

**Comment by knudmoeller** [comment]
That's awesome! I have to admit I didn't even know stuff like that was possible with gh-actions. I'll try to dig into this a little over the weekend to see how far I get. Since I don't want to use JS (I don't want to write any new code), I'm assuming I'd have to start with a docker container action and run the Ruby scraper within that?

**Comment by jaimergp** [comment]
I don't think you need a container. You'd need 4 steps:

1. Checkout repo
2. Install dependencies
3. Build JSON
4. Push to target location

I do something similar for some documentation (e.g. [here](https://github.com/openkinome/kinoml/blob/master/.github/workflows/docs.yaml)). That last step pushes to `gh-pages` by default. I don't know how it'd react to pushing to `master` as well (could trigger an infinite loop of push->CI->push->CI, etc), but maybe there's a way to filter the events based on the location of changed files (you could ignore pushes that only add changes in the directory that contains the released JSONs).

**Comment by knudmoeller** [comment]
Finally, after two weeks, I got around to writing that GitHub Actions workflow. It seems to work fine, but I'll let it run in a [separate branch](https://github.com/knudmoeller/berlin_corona_cases/tree/feature/gh-actions) for a few days before moving it to `master`. Thanks for the inspiration!

**Comment by knudmoeller** [comment]
It's in `master` (looks like that is the only branch where schedule-triggers work) now and seems to work well. I have written a few words about it [in the README](https://github.com/knudmoeller/berlin_corona_cases#running-automatically-with-github-actions) as well.

**Comment by jaimergp** [comment]
Awesome! Seems to be working perfectly! Thanks for the mention ;)
